host_name: vyos2
interfaces:
    - name: lo
      type: loopback
      description: ":loopback:lo0"
      ip: 192.160.0.3/32
      ip6: 2001:db8:1:0::3/128
    - name: eth5
      type: ethernet
      description: "seg5:vqfx2:em7"
      ip: 10.10.5.1/31
      ip6: 2001:db8:0:5::1/127
    - name: eth6
      type: ethernet
      description: "seg6:vyos1:eth6"
      ip: 10.10.6.1/31
      ip6: 2001:db8:0:6::1/127
bgp_asn: 65003
bgp_neighbors:
    - description: vqfx2
      asn: 65002
      ip: 10.10.5.0
      ip6: "2001:db8:0:5::"
    - description: vyos1
      asn: 65001
      ip: 10.10.6.0
      ip6: "2001:db8:0:6::"
