host_name: vqfx2
interfaces:
    - name: lo0
      type: loopback
      ip: 192.168.0.3/32
      ip6: 2001:db8:1::3/128
      host_network: false
    - name: xe-0/0/0
      type: ethernet
      ip: 10.10.0.1/31
      ip6: 2001:db8::1/127
      host_network: false
    - name: xe-0/0/3
      type: ethernet
      ip: 10.10.3.1/31
      ip6: 2001:db8:0:3::1/127
      host_network: false
    - name: xe-0/0/4
      type: ethernet
      ip: 10.100.1.1/24
      ip6: 2001:db8:0:ff01::1/64
      host_network: true
bgp_asn: 65003
bgp_neighbors:
    - description: vqfx1
      asn: 65000 
      ip: 10.10.0.0
      ip6: "2001:db8::"
    - description: vyos2
      asn: 65002
      ip: 10.10.3.0
      ip6: "2001:db8:0:3::"

