host_name: vyos2
interfaces:
    - name: lo
      type: loopback
      ip: 192.168.0.2/32
      ip6: 2001:db8:1:0::2/128
      host_network: false
    - name: eth3
      type: ethernet
      ip: 10.10.2.1/31
      ip6: 2001:db8:0:2::1/127
      host_network: false
    - name: eth4
      type: ethernet
      ip: 10.10.3.0/31
      ip6: 2001:db8:0:3::/127
      host_network: false
bgp_asn: 65002
bgp_neighbors:
    - description: vqfx2
      asn: 65001
      ip: 10.10.2.0
      ip6: "2001:db8:0:2::"
    - description: vyos1
      asn: 65003
      ip: 10.10.3.1
      ip6: "2001:db8:0:3::1"
